// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Aggregate-function registration via raw libduckdb-sys.
//!
//! Phase 3c (2026-06-24, unblocked once we forked duckdb-rs to
//! expose `Connection::handle()`): walks every shim aggregate
//! and wires it into DuckDB through the C API directly.
//!
//! Architecture
//!
//!   Per-aggregate-registration `ExtraInfo` allocation holds
//!   `Arc<dyn AggregateFunctionDef>`. The pointer is stashed on
//!   the duckdb_aggregate_function via
//!   `duckdb_aggregate_function_set_extra_info` and recovered
//!   in every callback via `duckdb_aggregate_function_get_extra_info`.
//!
//!   Per-group state (DuckDB allocates `state_size` bytes per
//!   group) is exactly 8 bytes: the thin pointer to a heap
//!   `Box<Box<dyn Accumulator>>`. `state_init` mints one;
//!   `state_destroy` drops it.
//!
//!   `update` walks the input chunk row-by-row, recovering the
//!   per-group accumulator via the thin pointer; `combine`
//!   merges source into target; `finalize` produces the result
//!   and writes it to the output vector slot.

use std::ffi::CString;
use std::os::raw::{c_char, c_void};
use std::sync::Arc;

use libduckdb_sys::{
    self as ffi, duckdb_aggregate_function_add_parameter, duckdb_aggregate_function_get_extra_info,
    duckdb_aggregate_function_set_error, duckdb_aggregate_function_set_extra_info,
    duckdb_aggregate_function_set_functions, duckdb_aggregate_function_set_name,
    duckdb_aggregate_function_set_return_type, duckdb_aggregate_state, duckdb_connection,
    duckdb_create_aggregate_function, duckdb_data_chunk, duckdb_destroy_aggregate_function,
    duckdb_function_info, duckdb_register_aggregate_function, duckdb_string_t, duckdb_vector,
    idx_t, DuckDBSuccess,
};

use datafission_functions::traits::{Accumulator, AggregateFunctionDef};
use datafission_functions::types::FunctionValue;

use crate::registry;

/// Per-registration state. Stashed on the aggregate via
/// duckdb_aggregate_function_set_extra_info; recovered in every
/// callback.
struct AggExtraInfo {
    def: Arc<dyn AggregateFunctionDef>,
}

/// Register every aggregate the shim publishes.
///
/// # Safety
///
/// `conn` must be a valid `duckdb_connection` for the duration
/// of this call.
pub unsafe fn register_all(conn: duckdb_connection) {
    register_aggregate(conn, "st_3dextent");
    register_aggregate(conn, "st_3d_extent"); // alias of st_3dextent
    register_aggregate(conn, "st_clusterdbscan");
    register_aggregate(conn, "st_cluster_dbscan"); // alias of st_clusterdbscan
    register_aggregate(conn, "st_clusterintersecting");
    register_aggregate(conn, "st_cluster_intersecting"); // alias of st_clusterintersecting
    register_aggregate(conn, "st_cluster_intersecting_aggregate"); // alias of st_clusterintersecting
    register_aggregate(conn, "st_clusterintersectingaggregate"); // alias of st_clusterintersecting
    register_aggregate(conn, "st_clusterwithin");
    register_aggregate(conn, "st_cluster_within"); // alias of st_clusterwithin
    register_aggregate(conn, "st_cluster_within_aggregate"); // alias of st_clusterwithin
    register_aggregate(conn, "st_clusterwithinaggregate"); // alias of st_clusterwithin
    register_aggregate(conn, "st_collect");
    register_aggregate(conn, "st_coverageunion");
    register_aggregate(conn, "st_coverage_union"); // alias of st_coverageunion
    register_aggregate(conn, "st_extent");
    register_aggregate(conn, "st_makeline");
    register_aggregate(conn, "st_make_line"); // alias of st_makeline
    register_aggregate(conn, "st_make_line_aggregate"); // alias of st_makeline
    register_aggregate(conn, "st_makelineagg"); // alias of st_makeline
    register_aggregate(conn, "st_makelineaggregate"); // alias of st_makeline
    register_aggregate(conn, "st_polygonize");
    register_aggregate(conn, "st_polygonize_aggregate"); // alias of st_polygonize
    register_aggregate(conn, "st_polygonizeagg"); // alias of st_polygonize
    register_aggregate(conn, "st_polygonizeaggregate"); // alias of st_polygonize
    register_aggregate(conn, "st_rast_union");
    register_aggregate(conn, "st_rast_union_aggregate"); // alias of st_rast_union
    register_aggregate(conn, "st_raster_union"); // alias of st_rast_union
    register_aggregate(conn, "st_union");
    register_aggregate(conn, "st_mem_union"); // alias of st_union
    register_aggregate(conn, "st_memunion"); // alias of st_union
    register_aggregate(conn, "st_union_aggregate"); // alias of st_union
    register_aggregate(conn, "st_unionagg"); // alias of st_union
    register_aggregate(conn, "st_unionaggregate"); // alias of st_union
                                                   // Phase 3c: 11 canonical + 23 alias names registered.
}

unsafe fn register_aggregate(conn: duckdb_connection, sql_name: &str) {
    let def = match registry::lookup_aggregate(sql_name) {
        Some(d) => d,
        None => {
            eprintln!("[shim-aggregates] no shim entry for `{sql_name}` — skipping");
            return;
        }
    };

    let agg = duckdb_create_aggregate_function();
    let name_cs = match CString::new(sql_name) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-aggregates] name contains NUL: `{sql_name}` — skipping");
            duckdb_destroy_aggregate_function(&mut { agg });
            return;
        }
    };
    duckdb_aggregate_function_set_name(agg, name_cs.as_ptr());

    // PostGIS aggregates are unary (ST_Union, ST_Extent,
    // ST_Collect — all take one geometry blob). For multi-arg
    // future aggregates, walk def.param_types() and call
    // add_parameter per type. Today's flat BLOB signature is
    // shape-correct for every shim aggregate observed.
    let blob = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB);
    duckdb_aggregate_function_add_parameter(agg, blob);
    duckdb_aggregate_function_set_return_type(agg, blob);
    // Both add_parameter and set_return_type take the type by
    // value and DuckDB clones it internally, so we still own
    // `blob` and have to destroy it after use.
    let mut blob_to_destroy = blob;
    ffi::duckdb_destroy_logical_type(&mut blob_to_destroy);

    // Wire the callbacks (state_size + state_init + update +
    // combine + finalize). state_destroy goes through the
    // separate set_destructor API — see drop_state below.
    duckdb_aggregate_function_set_functions(
        agg,
        Some(state_size),
        Some(state_init),
        Some(update_callback),
        Some(combine_callback),
        Some(finalize_callback),
    );
    ffi::duckdb_aggregate_function_set_destructor(agg, Some(state_destroy));

    // Park the per-registration state. The Box is leaked here
    // and reclaimed when DuckDB calls the destructor.
    let extra = Box::into_raw(Box::new(AggExtraInfo {
        def: Arc::clone(&def),
    }));
    duckdb_aggregate_function_set_extra_info(agg, extra as *mut c_void, Some(drop_extra_info));

    let rc = duckdb_register_aggregate_function(conn, agg);
    duckdb_destroy_aggregate_function(&mut { agg });
    if rc != DuckDBSuccess {
        // 5 PostGIS aggregate names clash with scalar variants
        // (st_collect, st_union, st_clusterwithin,
        // st_clusterdbscan, st_clusterintersecting). DuckDB
        // rejects the registration in that case. Swallow the
        // error so the non-clashing aggregates still register —
        // the clashing ones fall back to the already-registered
        // scalar form, which has the semantics the user probably
        // wanted anyway.
        eprintln!(
            "postgis-duckdb-bridge: skipping aggregate `{sql_name}` \
             (name already in use by a scalar; rc={rc})"
        );
    }
}

// =====================================================================
// C callbacks. All `unsafe extern "C"` because DuckDB calls them.
//
// State layout: each per-group state is exactly 8 bytes — a
// thin pointer to a heap-allocated `Box<dyn Accumulator>`.
// `state_init` mints one; `state_destroy` drops it. We use
// Box<dyn Accumulator> directly (fat ptr → 16 bytes) but stored
// behind one more Box layer so the THIN pointer is what lives
// in the state slot.
// =====================================================================

type AccBoxPtr = *mut Box<dyn Accumulator>;

unsafe extern "C" fn state_size(_info: duckdb_function_info) -> idx_t {
    std::mem::size_of::<AccBoxPtr>() as idx_t
}

unsafe extern "C" fn state_init(info: duckdb_function_info, state: duckdb_aggregate_state) {
    let extra = extra_info_typed(info);
    let acc: Box<dyn Accumulator> = extra.def.create_accumulator();
    let thin: AccBoxPtr = Box::into_raw(Box::new(acc));
    // The state pointer points to STATE_SIZE bytes that DuckDB
    // owns. Treat it as a slot for our thin pointer.
    let slot = state as *mut AccBoxPtr;
    std::ptr::write(slot, thin);
}

unsafe extern "C" fn state_destroy(states: *mut duckdb_aggregate_state, count: idx_t) {
    if states.is_null() {
        return;
    }
    for i in 0..count as usize {
        let state_ptr: duckdb_aggregate_state = std::ptr::read(states.add(i));
        if state_ptr.is_null() {
            continue;
        }
        let slot = state_ptr as *mut AccBoxPtr;
        let thin = std::ptr::read(slot);
        if !thin.is_null() {
            drop(Box::from_raw(thin));
        }
    }
}

unsafe extern "C" fn update_callback(
    info: duckdb_function_info,
    input: duckdb_data_chunk,
    states: *mut duckdb_aggregate_state,
) {
    match std::panic::catch_unwind(|| update_inner(info, input, states)) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => set_error(info, &msg),
        Err(_) => set_error(info, "panic in aggregate update"),
    }
}

unsafe fn update_inner(
    _info: duckdb_function_info,
    input: duckdb_data_chunk,
    states: *mut duckdb_aggregate_state,
) -> std::result::Result<(), String> {
    let n = ffi::duckdb_data_chunk_get_size(input) as usize;
    let v0 = ffi::duckdb_data_chunk_get_vector(input, 0);
    let data = ffi::duckdb_vector_get_data(v0) as *const duckdb_string_t;
    let validity = ffi::duckdb_vector_get_validity(v0);

    for i in 0..n {
        if !validity.is_null() && !ffi::duckdb_validity_row_is_valid(validity, i as idx_t) {
            // SQL aggregates skip NULLs unless they're COUNT(*) —
            // PostGIS aggregates all skip NULL.
            continue;
        }
        let mut s_raw: duckdb_string_t = std::ptr::read(data.add(i));
        let bytes = read_string_t_bytes(&mut s_raw);
        let acc_ptr = read_state(states, i);
        let acc = &mut *acc_ptr;
        acc.accumulate(&FunctionValue::Binary(bytes))
            .map_err(|e| format!("{e:?}"))?;
    }
    Ok(())
}

/// Decode a `duckdb_string_t` (DuckDB's inline-or-pointer
/// string struct) into an owned `Vec<u8>`. Works for both
/// inlined (≤12 bytes) and pointer-backed strings; the C API
/// hides the discriminant for us.
unsafe fn read_string_t_bytes(s: &mut duckdb_string_t) -> Vec<u8> {
    let len = ffi::duckdb_string_t_length(*s) as usize;
    if len == 0 {
        return Vec::new();
    }
    let p = ffi::duckdb_string_t_data(s as *mut duckdb_string_t);
    std::slice::from_raw_parts(p as *const u8, len).to_vec()
}

unsafe extern "C" fn combine_callback(
    info: duckdb_function_info,
    source: *mut duckdb_aggregate_state,
    target: *mut duckdb_aggregate_state,
    count: idx_t,
) {
    let result = std::panic::catch_unwind(|| {
        for i in 0..count as usize {
            let src = read_state(source, i);
            let tgt = read_state(target, i);
            if src.is_null() || tgt.is_null() {
                continue;
            }
            let src_acc: &dyn Accumulator = &**src;
            let tgt_acc = &mut **tgt;
            tgt_acc.merge(src_acc).map_err(|e| format!("{e:?}"))?;
        }
        Ok::<(), String>(())
    });
    match result {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => set_error(info, &msg),
        Err(_) => set_error(info, "panic in aggregate combine"),
    }
}

unsafe extern "C" fn finalize_callback(
    info: duckdb_function_info,
    source: *mut duckdb_aggregate_state,
    result: duckdb_vector,
    count: idx_t,
    offset: idx_t,
) {
    match std::panic::catch_unwind(|| finalize_inner(info, source, result, count, offset)) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => set_error(info, &msg),
        Err(_) => set_error(info, "panic in aggregate finalize"),
    }
}

unsafe fn finalize_inner(
    _info: duckdb_function_info,
    source: *mut duckdb_aggregate_state,
    result: duckdb_vector,
    count: idx_t,
    offset: idx_t,
) -> std::result::Result<(), String> {
    for i in 0..count as usize {
        let dst = offset as usize + i;
        let acc_ptr = read_state(source, i);
        if acc_ptr.is_null() {
            vector_set_null(result, dst);
            continue;
        }
        let acc = &**acc_ptr;
        let value = acc.finalize().map_err(|e| format!("{e:?}"))?;
        match value {
            FunctionValue::Binary(b) => vector_assign_bytes(result, dst, &b),
            FunctionValue::String(s) => vector_assign_bytes(result, dst, s.as_bytes()),
            FunctionValue::Null => vector_set_null(result, dst),
            other => {
                return Err(format!(
                    "aggregate finalize: unexpected result variant `{}`",
                    other.type_name()
                ))
            }
        }
    }
    Ok(())
}

/// Write `bytes` into the `dst`-th slot of `result` (a BLOB or
/// VARCHAR output vector). DuckDB copies the bytes internally,
/// so the caller's `bytes` can be dropped after this call.
unsafe fn vector_assign_bytes(result: duckdb_vector, dst: usize, bytes: &[u8]) {
    ffi::duckdb_vector_assign_string_element_len(
        result,
        dst as idx_t,
        bytes.as_ptr() as *const c_char,
        bytes.len() as idx_t,
    );
}

/// Mark the `dst`-th slot of `result` as SQL NULL.
unsafe fn vector_set_null(result: duckdb_vector, dst: usize) {
    ffi::duckdb_vector_ensure_validity_writable(result);
    let validity = ffi::duckdb_vector_get_validity(result);
    if !validity.is_null() {
        ffi::duckdb_validity_set_row_invalid(validity, dst as idx_t);
    }
}

unsafe extern "C" fn drop_extra_info(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }
    drop(Box::from_raw(ptr as *mut AggExtraInfo));
}

// =====================================================================
// State-slot accessors.
// =====================================================================

unsafe fn read_state(states: *mut duckdb_aggregate_state, idx: usize) -> AccBoxPtr {
    // `states[i]` is a duckdb_aggregate_state (a pointer to the
    // per-group state slot). Dereference to get the slot
    // address, then read our AccBoxPtr out of the slot.
    //
    // (Initial implementation skipped the dereference and
    // crashed DuckDB with SIGBUS — the C API docs say:
    //   "states – a pointer to states – Each element points to
    //    the state for the corresponding input row."
    //  i.e. it's an array of state pointers, not the states
    //  themselves laid out contiguously.)
    let state_ptr: duckdb_aggregate_state = std::ptr::read(states.add(idx));
    let slot = state_ptr as *mut AccBoxPtr;
    std::ptr::read(slot)
}

unsafe fn extra_info_typed<'a>(info: duckdb_function_info) -> &'a AggExtraInfo {
    let raw = duckdb_aggregate_function_get_extra_info(info);
    &*(raw as *const AggExtraInfo)
}

unsafe fn set_error(info: duckdb_function_info, msg: &str) {
    if let Ok(cs) = CString::new(msg) {
        duckdb_aggregate_function_set_error(info, cs.as_ptr() as *const c_char);
    }
}
