// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Operator handling.
//!
//! ## Phase 4d — same architectural blocker as sqlink
//! (2026-06-24)
//!
//! DuckDB's parser tokenises operators at compile time too.
//! Custom symbols like `&&&` or `<#>` are unrecognised tokens
//! — `SELECT g1 &&& g2` is a parse error before any function
//! dispatch could intervene. DuckDB DOES recognise some
//! symbols (`<<`, `>>`, etc.) and could in principle bind them
//! to scalar functions, but the registration API isn't exposed
//! from duckdb-rs (same Connection-internals problem).
//!
//! ## Where this work actually lives
//!
//! SQL-preprocessing concern, not extension concern. The
//! proper home is a separate `ducklink-preprocess` crate that:
//!
//!   - Parses SQL via sqlparser-rs (DuckDB dialect)
//!   - Rewrites operators: `g1 && g2` → `st_bboxintersects(g1, g2)`
//!   - Rewrites casts to user-types: same approach
//!   - Hands rewritten SQL to duckdb-rs's `prepare`/`execute`
//!
//! That crate can be generated from the same BridgePlan but
//! is a separate target.

use duckdb::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Operators the shim advertises.
// ----------------------------------------------------------------------

// === extension: postgis ===
// `##` (lhs=Some(2001), rhs=Some(2001))  →  st_intersection
// `&&` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxintersects
// `&&` (lhs=Some(2003), rhs=Some(2003))  →  st_intersects
// `&&&` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxintersectsnd
// `&&|` (lhs=Some(2001), rhs=Some(2001))  →  st_intersects
// `&<` (lhs=Some(2001), rhs=Some(2001))  →  st_overlaps
// `&<` (lhs=Some(2003), rhs=Some(2003))  →  st_overlaps
// `&<>` (lhs=Some(2001), rhs=Some(2001))  →  st_disjoint
// `&>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxoverright
// `<#>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxdistance
// `<->` (lhs=Some(2001), rhs=Some(2001))  →  st_knndistance
// `<<` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxleftof
// `<<|` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxbelow
// `<@` (lhs=Some(2001), rhs=Some(2001))  →  st_within
// `<@` (lhs=Some(2003), rhs=Some(2003))  →  st_within
// `>>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxrightof
// `@>` (lhs=Some(2001), rhs=Some(2001))  →  st_contains
// `@>` (lhs=Some(2003), rhs=Some(2003))  →  st_contains
// `|>>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxabove
// `||` (lhs=Some(2001), rhs=Some(2001))  →  st_union
// `~` (lhs=Some(2001), rhs=Some(2001))  →  st_contains
// `~=` (lhs=Some(2001), rhs=Some(2001))  →  st_geomequal
// `~=` (lhs=Some(2003), rhs=Some(2003))  →  st_equals
