// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Shim registry — loads the composed wasm shim exactly once
//! at extension-init time and exposes a name → ScalarFunctionDef
//! lookup for the per-call dispatcher.
//!
//! Architecture is identical to sqlink's registry; the only
//! reason it lives here too is so the generated DuckDB bridge
//! is self-contained (no cross-bridge deps).

use std::collections::HashMap;
use std::sync::Arc;

use anyhow::{Context, Result};
use once_cell::sync::OnceCell;
use parking_lot::RwLock;

use datafission_df_plugin_api::{
    DataTypePlugin, Extension, ExtensionError, ExtensionTarget, SystemCatalogProvider,
};
use datafission_df_plugin_loader::RuntimeWasmExtension;
use datafission_functions::traits::{
    AggregateFunctionDef, ScalarFunctionDef, TableFunctionDef, WindowFunctionDef,
};

/// Lazily-loaded shim handle. Initialised in `load_shim()` from
/// the `POSTGIS_SHIM_WASM` env var.
static SHIM: OnceCell<ShimRegistry> = OnceCell::new();

struct ShimRegistry {
    _ext: RuntimeWasmExtension, // keep the wasm Store alive
    scalars: RwLock<HashMap<String, Arc<dyn ScalarFunctionDef>>>,
    aggregates: RwLock<HashMap<String, Arc<dyn AggregateFunctionDef>>>,
}

pub fn load_shim() -> Result<()> {
    if SHIM.get().is_some() {
        return Ok(());
    }
    let path = std::env::var("POSTGIS_SHIM_WASM").with_context(|| {
        format!("Set POSTGIS_SHIM_WASM=/path/to/composed-shim.wasm before LOAD")
    })?;
    let ext =
        RuntimeWasmExtension::from_file(&path).with_context(|| format!("loading shim {path}"))?;

    let mut capture = CapturingTarget {
        scalars: Vec::new(),
        aggregates: Vec::new(),
    };
    ext.register(&mut capture)
        .map_err(|e| anyhow::anyhow!("shim register: {e}"))?;

    let mut scalars = HashMap::with_capacity(capture.scalars.len() * 2);
    for def in capture.scalars {
        let canonical = def.name().to_string();
        for alias in def.aliases() {
            scalars.insert(alias.to_string(), Arc::clone(&def));
        }
        scalars.insert(canonical, def);
    }
    let mut aggregates = HashMap::with_capacity(capture.aggregates.len() * 2);
    for def in capture.aggregates {
        let canonical = def.name().to_string();
        for alias in def.aliases() {
            aggregates.insert(alias.to_string(), Arc::clone(&def));
        }
        aggregates.insert(canonical, def);
    }

    SHIM.set(ShimRegistry {
        _ext: ext,
        scalars: RwLock::new(scalars),
        aggregates: RwLock::new(aggregates),
    })
    .map_err(|_| anyhow::anyhow!("ShimRegistry already initialised"))?;

    Ok(())
}

pub fn lookup_scalar(name: &str) -> Option<Arc<dyn ScalarFunctionDef>> {
    let r = SHIM.get()?;
    r.scalars.read().get(name).cloned()
}

pub fn lookup_aggregate(name: &str) -> Option<Arc<dyn AggregateFunctionDef>> {
    let r = SHIM.get()?;
    r.aggregates.read().get(name).cloned()
}

/// ExtensionTarget that captures every scalar and aggregate the
/// shim registers. UDTFs / windows / types / etc. are accepted
/// as no-ops until later phases.
struct CapturingTarget {
    scalars: Vec<Arc<dyn ScalarFunctionDef>>,
    aggregates: Vec<Arc<dyn AggregateFunctionDef>>,
}

impl ExtensionTarget for CapturingTarget {
    fn register_scalar_function(
        &mut self,
        _namespace: &str,
        def: Arc<dyn ScalarFunctionDef>,
    ) -> std::result::Result<(), ExtensionError> {
        self.scalars.push(def);
        Ok(())
    }
    fn register_aggregate_function(
        &mut self,
        _namespace: &str,
        def: Arc<dyn AggregateFunctionDef>,
    ) -> std::result::Result<(), ExtensionError> {
        self.aggregates.push(def);
        Ok(())
    }
    fn register_table_function(
        &mut self,
        _namespace: &str,
        _def: Arc<dyn TableFunctionDef>,
    ) -> std::result::Result<(), ExtensionError> {
        Ok(())
    }
    fn register_window_function(
        &mut self,
        _namespace: &str,
        _def: Arc<dyn WindowFunctionDef>,
    ) -> std::result::Result<(), ExtensionError> {
        Ok(())
    }
    fn register_data_type(
        &mut self,
        _plugin: Arc<dyn DataTypePlugin>,
    ) -> std::result::Result<(), ExtensionError> {
        Ok(())
    }
    fn register_system_catalog_provider(
        &mut self,
        _provider: Arc<dyn SystemCatalogProvider>,
    ) -> std::result::Result<(), ExtensionError> {
        Ok(())
    }
    fn as_any_mut(&mut self) -> &mut dyn std::any::Any {
        self
    }
}
