// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! System-catalog tables as DuckDB table functions with a
//! static schema (one TableFunction per virtual table).

// TODO: emit one register_table_function per catalog entry.
