// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Table-function registration.
//!
//! ## Phase 4c — SCAFFOLDED (2026-06-24)
//!
//! Unlike aggregates (Phase 3c) and custom types (Phase 4b),
//! DuckDB's TableFunction API IS exposed in duckdb-rs via
//! the `VTab` trait. The `hello-ext` example
//! (`~/.cargo/registry/.../duckdb-1.x/examples/hello-ext/main.rs`)
//! shows the canonical pattern: bind/init/func callbacks +
//! `con.register_table_function::<HelloVTab>("hello")`.
//!
//! Architecture for shipping this
//!
//!   1. Define one concrete `ShimVTab` type with a BindData
//!      that holds Arc<dyn TableFunctionDef> + the parameter
//!      values from the SQL call.
//!
//!   2. `bind` reads SQL params via `bind.get_parameter(i)`,
//!      builds the output column schema from
//!      `def.output_schema(...)`.
//!
//!   3. `init` creates a per-query InitData holding
//!      `Box<dyn TableFunctionIterator>` from
//!      `def.execute(&function_values)`.
//!
//!   4. `func` calls `iter.next_row()` repeatedly to fill the
//!      output DataChunk; sets output length when chunk full
//!      or iter exhausted.
//!
//! Same blocker as Phase 3c/4b — the way duckdb-rs threads
//! state through bind/init/func means each shim UDTF needs
//! its own per-name VTab struct (or unsafe shared state).
//! With 7 PostGIS UDTFs and 2-3 ducks of unsafe code per
//! per-UDTF impl, this is ~400 LOC that warrants its own
//! session.

use duckdb::{Connection, Result};

/// Phase-4c no-op. The shim's UDTFs are captured in the
/// registry; the day someone writes the ShimVTab adapter,
/// this becomes a loop over registry::all_table_functions().
pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// UDTFs the shim publishes.
// ----------------------------------------------------------------------

// === extension: postgis ===
// udtf `st_dump` (arity=1)
// udtf `st_dumppoints` (arity=1)
//   aliases: st_dump_points
// udtf `st_dumprings` (arity=1)
//   aliases: st_dump_rings
// udtf `st_dumpsegments` (arity=1)
//   aliases: st_dump_segments
// udtf `st_hexagongrid` (arity=2)
//   aliases: st_hexagon_grid
// udtf `st_squaregrid` (arity=2)
//   aliases: st_square_grid
// udtf `st_subdivide` (arity=1)
