// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Custom column types — alias BLOB as GEOMETRY, GEOGRAPHY, …
//!
//! Each shim type is registered with DuckDB as an alias for
//! `BLOB`. After registration `CREATE TABLE t (g GEOMETRY)`
//! shows `GEOMETRY` in the schema; storage and the function
//! ABI stay BLOB so existing `ScalarFunctionSignature::exact`
//! signatures keep working unchanged.
//!
//! For each registered type name we call:
//!
//!     handle = duckdb_create_logical_type(DUCKDB_TYPE_BLOB)
//!     duckdb_logical_type_set_alias(handle, "GEOMETRY")
//!     duckdb_register_logical_type(con, handle, NULL)
//!     duckdb_destroy_logical_type(handle)
//!
//! `duckdb_create_type_info` is reserved-for-future-use per
//! upstream comments — we pass NULL. On a name clash with an
//! existing type DuckDB returns DuckDBError; we log+continue
//! to match the policy aggregates_rs uses for scalar/aggregate
//! collisions.

use libduckdb_sys as ffi;
use std::ffi::CString;

/// Register every shim-published custom type as a BLOB alias.
///
/// # Safety
///
/// `con` must be a valid `duckdb_connection` for the duration
/// of this call.
pub unsafe fn register_all(con: ffi::duckdb_connection) {
    if con.is_null() {
        return;
    }
    register_type(con, "BOX2D");
    register_type(con, "BOX3D");
    register_type(con, "GEOGRAPHY");
    register_type(con, "GEOMETRY");
    register_type(con, "RASTER");
    register_type(con, "TOPOGEOMETRY");
    register_type(con, "VECTOR");
}

unsafe fn register_type(con: ffi::duckdb_connection, name: &str) {
    let handle = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB);
    if handle.is_null() {
        eprintln!("[shim-types] could not create logical type for {name}");
        return;
    }
    let c_name = match CString::new(name) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-types] type name contains NUL: {name}");
            let mut h = handle;
            ffi::duckdb_destroy_logical_type(&mut h);
            return;
        }
    };
    ffi::duckdb_logical_type_set_alias(handle, c_name.as_ptr());
    let rc = ffi::duckdb_register_logical_type(con, handle, std::ptr::null_mut());
    if rc != ffi::DuckDBSuccess {
        eprintln!(
            "[shim-types] could not register type {name} (rc={rc}) — \
             likely a name clash with an existing type"
        );
    }
    let mut h = handle;
    ffi::duckdb_destroy_logical_type(&mut h);
}

// ----------------------------------------------------------------------
// Column types the shim publishes.
// ----------------------------------------------------------------------

// === extension: postgis ===
// type_id= 2001 name=GEOMETRY                 size=  -1  cast_from=[]  cast_to=[]
// type_id= 2002 name=BOX2D                    size=  -1  cast_from=[]  cast_to=[]
// type_id= 2003 name=GEOGRAPHY                size=  -1  cast_from=[]  cast_to=[]
// type_id= 2004 name=RASTER                   size=  -1  cast_from=[]  cast_to=[]
// type_id= 2005 name=VECTOR                   size=  -1  cast_from=[]  cast_to=[]
// type_id= 2006 name=TOPOGEOMETRY             size=  -1  cast_from=[]  cast_to=[]
// type_id= 2007 name=BOX3D                    size=  48  cast_from=[]  cast_to=[]
