// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Window-function registration.
//!
//! DuckDB exposes window functions as a special aggregate
//! variant with extra hooks for partition + frame state.

// window `st_clusterdbscan`
// window `st_clusterintersectingwin`
// window `st_clusterkmeans`
// window `st_clusterwithinwin`

// TODO: wire window-capable aggregates.
